version: 2

jobs:
  run-tests:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Install Python requirements
          command: |
              pip install virtualenv
              virtualenv ~/venv
              source ~/venv/bin/activate
              pip install -r requirements.txt
              pip install Django==1.8.19
              pip install djangorestframework==3.2.5
      - run:
          name: Run Python tests
          command: |
              source ~/venv/bin/activate
              ./manage.py test --settings=test_settings

workflows:
  version: 2
  build-and-tests:
    jobs:
      - run-tests